### PR TITLE
CRUD Operations performed and checked

### PR DESCRIPTION
**Pull request by suu-b**
CRUD Operations were performed. The API was checked in every parameter. Minor typos were checked.

### CODE REVIEW

**Comment by ShubhamThakur025** [comment]
@CodiumAI-Agent /review

**Comment by ShubhamThakur025** [comment]
@CodiumAI-Agent /review

**Comment by suu-b** [comment]
@CodiumAI-Agent /review

**Comment by suu-b** [comment]
@CodiumAI-Agent /review

**Pull request merged**
